# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:55:54+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import AnyUrl, BaseModel, Field, constr


class ChannelEnumChannelType(Enum):
    public = 'public'
    private = 'private'


class ChannelEnumWebhookEnabledType(Enum):
    true = 'true'
    false = 'false'


class ChatV3Channel(BaseModel):
    account_sid: Optional[
        constr(pattern=r'^AC[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Channel resource.',
    )
    attributes: Optional[str] = Field(
        None,
        description='The JSON string that stores application-specific data. If attributes have not been set, `{}` is returned.',
    )
    created_by: Optional[str] = Field(
        None,
        description='The `identity` of the User that created the channel. If the Channel was created by using the API, the value is `system`.',
    )
    date_created: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    date_updated: Optional[datetime] = Field(
        None,
        description='The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.',
    )
    friendly_name: Optional[str] = Field(
        None, description='The string that you assigned to describe the resource.'
    )
    members_count: Optional[int] = Field(
        None, description='The number of Members in the Channel.'
    )
    messages_count: Optional[int] = Field(
        None, description='The number of Messages that have been passed in the Channel.'
    )
    messaging_service_sid: Optional[
        constr(pattern=r'^MG[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique ID of the [Messaging Service](https://www.twilio.com/docs/sms/services/api) this channel belongs to.',
    )
    service_sid: Optional[
        constr(pattern=r'^IS[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) the Channel resource is associated with.',
    )
    sid: Optional[
        constr(pattern=r'^CH[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique string that we created to identify the Channel resource.',
    )
    type: Optional[ChannelEnumChannelType] = Field(
        None,
        description='The visibility of the channel. Can be: `public` or `private`.',
    )
    unique_name: Optional[str] = Field(
        None,
        description="An application-defined string that uniquely identifies the resource. It can be used to address the resource in place of the resource's `sid` in the URL.",
    )
    url: Optional[AnyUrl] = Field(
        None, description='The absolute URL of the Channel resource.'
    )


class V3ServicesServiceSidChannelsSidPostRequest(BaseModel):
    MessagingServiceSid: Optional[
        constr(pattern=r'^MG[0-9a-fA-F]{32}$', min_length=34, max_length=34)
    ] = Field(
        None,
        description='The unique ID of the [Messaging Service](https://www.twilio.com/docs/sms/services/api) this channel belongs to.',
    )
    Type: Optional[ChannelEnumChannelType] = Field(
        None,
        description="TThe Type for this Channel to migrate to. Can only be `private`. Migration to 'public' is not allowed.",
    )
